name: GDCC Build (Ninja)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build (with Ninja and gdcc)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gdcc
        shell: bash
        working-directory: /tmp/
        run: |
          shopt -s globstar
          mkdir gdcc/
          pushd gdcc/

          # install gdcc bins and libs
          curl https://raw.githubusercontent.com/Gustavo6046/Indusferno/ci-deps/gdcc-bins.zip -ogdcc-bins.zip
          unzip gdcc-bins.zip
          chmod -v +x */gdcc-* **/*.so
          sudo mv -v */gdcc-* /usr/bin
          sudo mv -v **/*.so /usr/lib
          rm -rvf ./*

          # install gdcc headers
          curl https://raw.githubusercontent.com/Gustavo6046/Indusferno/ci-deps/gdcc-share-lib.zip -ogdcc-share-lib.zip
          unzip gdcc-share-lib.zip
          sudo mkdir -pv /usr/share/gdcc
          sudo mv -v lib/ /usr/share/gdcc/lib
          popd
          rm -rf gdcc/

      - name: Install build dependencies
        run: sudo apt install ninja-build

      - name: Build with ninja
        working-directory: ${{github.workspace}}
        run: ninja

      - name: Upload built ACS objects
        uses: actions/upload-artifact@v2
        with:
          name: acs-build
          path: ${{github.workspace}}/bin/

  assemble:
    name: Assemble (with ZDCode Zake)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        run: sudo apt install python3 python3-pip

      - name: Install ZDCode
        run: sudo pip install zdcode

      - name: Download last ACS build artifact
        uses: actions/download-artifact@v2
        with:
          name: acs-build
          latest: true
          path: ${{github.workspace}}/bin/

      - name: Run ZDCode
        working-directory: ${{github.workspace}}
        run: python3 -m zdcode .
      
      - name: Upload built packages
        uses: actions/upload-artifact@v2
        with:
          name: 
          path: ${{github.workspace}}/pkg/
