name: Ninja Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gdcc
        shell: bash
        working-directory: /tmp/
        run: |
          shopt -s globstar
          mkdir gdcc/
          pushd gdcc/

          # install gdcc bins and libs
          curl https://raw.githubusercontent.com/Gustavo6046/Indusferno/ci-deps/gdcc-bins.zip -ogdcc-bins.zip
          unzip gdcc-bins.zip
          chmod -v +x */gdcc-* **/*.so
          sudo mv -v */gdcc-* /usr/bin
          sudo mv -v **/*.so /usr/lib
          rm -rvf ./*

          # install gdcc headers
          curl https://raw.githubusercontent.com/Gustavo6046/Indusferno/ci-deps/gdcc-share-lib.zip -ogdcc-share-lib.zip
          unzip gdcc-share-lib.zip
          sudo mkdir -pv /usr/share/gdcc
          sudo mv -v lib/ /usr/share/gdcc/lib
          popd
          rm -rf gdcc/

      - name: Install build dependencies
        run: sudo apt install ninja-build

      - name: Build with ninja
        working-directory: ${{github.workspace}}
        run: ninja
