name: Documentation Build (Doxygen)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  doc:
    name: Doxygen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doxygen
        run: sudo apt install doxygen

      - name: Run doxygen
        working-directory: ${{github.workspace}}
        run: doxygen Doxyfile

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: doc-build
          path: ${{github.workspace}}/doc
