name: Documentation Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  doc:
    name: Doxygen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doxygen
        run: sudo apt install doxygen

      - name: Install Python
        run: sudo apt install python3 python3-pip

      - name: Install MkDocs with plugins
        run: |
          pip install \
            git+https://github.com/pieterdavid/mkdocs-doxygen-plugin \
            mkdocs-latest-release-plugin \
            mkdocs-git-committers-plugin-2 \
            git+https://github.com/rkoe/mkdocs-emailprotect \
            mkdocs-minify-plugin

      - name: Run MkDocs
        working-directory: ${{github.workspace}}
        run: mkdocs build

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: doc-build
          path: ${{github.workspace}}/site

      - name: Push documentation to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
