# This is a basic workflow to help you get started with Actions

name: Ninja Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gdcc
        shell: bash
        working-directory: /tmp/
        run: |
          mkdir gdcc/
          pushd gdcc/
          curl https://0x0.st/-ZfU.zip -ogdcc.zip
          unzip gdcc.zip
          chmod +x */gdcc-*
          sudo mv */gdcc-* /usr/bin
          popd
          rm -rvf gdcc/
      
      - name: Install build dependencies
        run: sudo apt install ninja-build

      - name: Build with ninja
        working-directory: ${{github.workspace}}
        run: ninja
