# This is a basic workflow to help you get started with Actions

name: Ninja Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gdcc
        shell: bash
        working-directory: /tmp/
        run: |
          shopt -s globstar
          mkdir gdcc/
          pushd gdcc/
          # install gdcc bins and libs
          curl https://github.com/Gustavo6046/Indusferno/raw/ci-deps/gdcc-bins.zip -ogdcc-bins.zip
          unzip gdcc-bins.zip
          chmod -v +x */gdcc-* **/*.so
          sudo mv -v */gdcc-* /usr/bin
          sudo mv -v **/*.so /usr/lib
          rm -rvf ./*
          # install gdcc headers
          curl https://github.com/Gustavo6046/Indusferno/raw/ci-deps/gdcc-share-lib.zip -ogdcc-share-lib.zip
          unzip gdcc-share-lib.zip
          sudo mkdir -pv /usr/share/gdcc
          sudo mv -v lib/ /usr/share/gdcc/lib
          popd
          rm -rf gdcc/
      
      - name: Install build dependencies
        run: sudo apt install ninja-build

      - name: Build with ninja
        working-directory: ${{github.workspace}}
        run: ninja
